name: tracking_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  get: any
  flutter_background_service_ios: ^2.4.0
  flutter_background_service_android: ^3.0.2
  change_app_package_name: ^1.1.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  flutter_local_notifications: ^13.0.0

  http: ^0.13.5
  background_location:
    path: background_location-master

  firebase_core: ^2.8.0
  firebase_core_platform_interface: ^4.5.3
  get_storage: ^2.1.1
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  maps_launcher: ^2.2.0

  progress_dialog: ^1.2.4
  sliding_switch: ^1.1.0
  skeletons: ^0.0.3
  firebase_messaging: ^14.3.0
  flutter_background_service: ^2.4.6
  device_info_plus: ^8.1.0






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map_style.txt